### ISSUE TITLE
Variable Type to Future.traverse Try[List[int]]

### ISSUE THREAD

**Issue by alexkassil** [vickumar1981/functional_python#2]
Great talk today Vic! It was cool seeing so many functional patterns in python. 

Just wanted to leave my comment from the talk here about using Try[List[int]] instead of List[int] on page 14 here https://github.com/vickumar1981/functional_python/blob/master/functional-python.pdf for handle_result's result variable. 

I hope to use pyeffects for a personal coding project soon :)

**Comment by vickumar1981** [comment]
@alexkassil   great catch!!

I see what I did, right before I call the `handle_result` callback, I do a `.get` which unboxes the `Try[List[int]]` to a `List[int]`.

```
# Convert List[Future[int]] -> Future[List[int]] 
Future.traverse([result1, result2])\
    .on_complete(lambda v: handle_result(v.get(), start_time))
```

I think this is confusing, so I'm going to update the signature of the function and unbox the `Try` inside of `handle_result`.

**Comment by vickumar1981** [comment]
Addressed by commit: https://github.com/vickumar1981/functional_python/commit/ddf89486cdc88986c73041684ee6040d86ac9b3d
